// AWS Configuration - Auto-generated by unified deployment script
// Generated: Sun Jul 20 17:07:10 CDT 2025
// Stack: robot-puzzle-game-prod
// Region: us-east-1

const AWS_CONFIG = {
    region: 'us-east-1',
    cognito: {
        userPoolId: 'us-east-1_DSwZJ47Hd',
        userPoolWebClientId: '6u3frgcgb8806tt99bs1kk6lak'
    },
    api: {
        baseUrl: 'https://ctoxyuyx6a.execute-api.us-east-1.amazonaws.com/prod'
    }
};

// Export for Node.js environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = AWS_CONFIG;
}
