// AWS Configuration - Auto-generated by deploy script
// Generated: Tue Jun 24 21:31:17 CDT 2025
// Stack: robot-puzzle-game-dev
// Region: us-east-1

const AWS_CONFIG = {
    region: 'us-east-1',
    cognito: {
        userPoolId: 'us-east-1_BQP4SViZr',
        userPoolWebClientId: '6clckgr9b1jv8lp58isdj1bc9'
    },
    api: {
        baseUrl: 'https://a2unurbm99.execute-api.us-east-1.amazonaws.com/prod'
    }
};

// Export for Node.js environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = AWS_CONFIG;
}
